### ISSUE TITLE
Determine new best default values for row group and file size

### ISSUE THREAD

**Issue by alexr-bq** [vertica/spark-connector#132]
There is a bug, now fixed, that may cause Vertica to reserve much more disk space than needed for an export. For maximal support of older Vertica versions, we should investigate how the row group and file size params effect this happening, and change the default values to reflect this. 

Acceptance criteria:
- Report on how these parameters affect this bug
- Change of default parameters to reflect this
- Change to performance guide reflecting how to modify these parameters for optimal performance

**Comment by NerdLogic** [comment]
Has the fix been patched on earlier versions of vertica?  If so, it is probably not necessary to investigate this.

**Comment by alexey-temnikov** [comment]
Fix for the issue that may cause Vertica to reserve much more disk space than needed for an export is addressed in Vertica (and planned to be available on earlier versions). Closing this ticket.
