### ISSUE TITLE
Investigate bug with files not existing

### ISSUE THREAD

**Issue by jonathanl-bq** [vertica/spark-connector#147]
Investigate bug with files not existing

Acceptance Criteria:
- Document and confirm issue
- Reproduce environment

**Comment by alexr-bq** [comment]
Previously, we would copy with a unique ID unless the filters were the same. This was based on a confusion between the planInputPartitions and scan build functions. The former is called twice per operation, and it was assumed the later was as well. This is not the case, so there is no need to filter the copying, we can always copy with a new unique ID.
