### ISSUE TITLE
Set up Eon Accelerator to test our connector

### ISSUE THREAD

**Issue by ravjotbrar** [vertica/spark-connector#160]
- As a user you will log into https://www.vertica.com/accelerator and use that interface to talk indirectly with your own secure cloud. The link between the customer cloud and Vertica cloud is established during onboarding using cross account IAM access. Currently no fee for duration of the early access program, as  customer just needs to take care of their own AWS bill. Comes with 5 databases per account and primary + 3 sub-clusters per databases

What do I need to get started?
- AWS account 
- AWS admin access to setup cross account IAM access

**Comment by alexey-temnikov** [comment]
If additional examples are needed with EON mode, please comment/reopen the issue.
