### ISSUE TITLE
Spike: complex types

### ISSUE THREAD

**Issue by ravjotbrar** [vertica/spark-connector#163]
Currently, the V2 connector does not support complex data types (ARRAY, MAP, ROW). Trying to convert Vertica's ARRAYs into Spark ArrayTypes is a bit complicated due to ArrayType being abstract.

- Gather knowledge from Vertica team on what changed w/ complex types in 11.0 - specifically w/ regards to parquet export and copy
- Prototype
- Split into task(s)

**Comment by jeremyp-bq** [comment]
See complex types in Vertica [here](https://www.vertica.com/docs/11.0.x/HTML/Content/Authoring/SQLReferenceManual/DataTypes/ExternalTypes.htm), and Spark types, including complex, [here](https://spark.apache.org/docs/latest/sql-ref-datatypes.html).
