### ISSUE TITLE
Add code coverage badge to github

### ISSUE THREAD

**Issue by ravjotbrar** [vertica/spark-connector#167]
Commit or codecov based solution.

https://app.codecov.io/gh/vertica/spark-connector

**Comment by jeremyp-bq** [comment]
If going with codecov.io, see example for Scala and GiHub Actions here:
https://about.codecov.io/blog/how-to-set-up-codecov-with-scala-and-github-actions/

Should also add the license and test results from GitHub actions, for example:
```
[![License](https://img.shields.io/badge/License-Apache%202.0-orange.svg)](https://opensource.org/licenses/Apache-2.0)
[![Tests-CI](https://github.com/vertica/spark-connector/actions/workflows/main.yml/badge.svg)](https://github.com/vertica/spark-connector/actions/workflows/main.yml)
[![codecov](https://codecov.io/gh/vertica/spark-connector/branch/main/graph/badge.svg?token=<TOKEN>)](https://codecov.io/gh/vertica/spark-connector)
```

**Comment by jeremyp-bq** [comment]
If we don't use codecov, we may be able to run a coverage report:
```
sbt coverage test coverageReport
```

Then create a badge using an existing action, or create our own:
* https://github.com/marketplace/actions/dynamic-badges
* https://github.com/marketplace/actions/badge-action
* Directly against shields.io (e.g. https://itnext.io/github-actions-code-coverage-without-third-parties-f1299747064d)
