### ISSUE TITLE
Schema mismatch: option for logging example data

### ISSUE THREAD

**Issue by ravjotbrar** [vertica/spark-connector#173]
It's been requested to log an example of data that doesn't match schema. If added this should be an option as logging real data by default is a security concern.

Will be good to check this issue together with #293

**Comment by jeremyp-bq** [comment]
We should investigate to see if the rejected rows behaviour covers this or not (it will print out an example of each type of rejected row), otherwise we should add similar functionality to where we are throwing an exception on schema mismatch and print an example row that does not match the schema.

**Comment by alexey-temnikov** [comment]
Downgrading to Normal priority, as it is applicable for development / debugging purposes only.
