### ISSUE TITLE
Detail caveats around data type conversion in End User documentation

### ISSUE THREAD

**Issue by ravjotbrar** [vertica/spark-connector#174]
Our End User documentation should detail the caveats around data type conversion and potential truncation (i.e. StringType to VARCHAR/LONG VAR CHAR). If Spark's type sizes are unbounded, people need to know what the behaviour will be when going into Vertica.

**Comment by jonathanl-bq** [comment]
Closing because there are no known changes in data type conversion between V1 and V2 connectors.
