### ISSUE TITLE
[SPIKE] Single source of truth for connector version

### ISSUE THREAD

**Issue by ravjotbrar** [vertica/spark-connector#218]
For every new connector release, the connector version needs to be updated in multiple files. Need to find a solution that only requires an update of the connector version in one place, which is then propagated to all other files.

**Comment by jeremyp-bq** [comment]
This was addressed in 3.1.0 by adding a `version.properties` file that contains the current version and is used by _most_ places in the repo.  There are now only a couple of READMEs and an R file that need updating when incrementing the version, in addition to the `version.properties` file.
