### ISSUE TITLE
Support https with dfs.namenode with delegation tokens

### ISSUE THREAD

**Issue by alexr-bq** [vertica/spark-connector#219]
https://github.com/vertica/spark-connector/blob/main/connector/src/main/scala/com/vertica/spark/datasource/jdbc/VerticaJdbcLayer.scala#L354

We use dfs.namenode.http-address, should also support https-address

First, reproduce problems when an https-address is used. Then add support for it with delegation tokens.

**Comment by jonathanl-bq** [comment]
Update: Currently trying to connect to secure webhdfs using Kerberos via our Docker setup. We've been dealing with several errors due to differences in how webhdfs works and how it is set up. The issue we currently face is this: "Security enabled but user not authenticated by filter".
