### ISSUE TITLE
Update Sparklyr and PySpark documentation

### ISSUE THREAD

**Issue by ravjotbrar** [vertica/spark-connector#222]
Currently, the documentation for these examples requires the user to run sbt assembly on the connector. This needs to be updated to show how we can source the connector jar without having to use sbt.

**Comment by jeremyp-bq** [comment]
Resolved by #246, where the documentation was already updated previously.

I am able to run both the PySpark and sparklyr examples without issue (after building the connector JAR in the documented location).
