### ISSUE TITLE
External tables: implement solution to get around truncation warning

### ISSUE THREAD

**Issue by ravjotbrar** [vertica/spark-connector#289]
Currently, when users want to create an external table using data existing in hdfs, theyget a warning about their data being truncated if it contains columns of varchar and varbinary types. This happens because the function used to infer the schema does not infer the sizes of those column types. 

Therefore, we need to implement a solution that will be able to override the sizes of these columns. (Possibly using a new connector option).

**Comment by alexey-temnikov** [comment]
The current issue text will be truncated to max of 80 characters and we do not provide a mechanism to increase the limit. As part of this issue, we will explore the mechanism of how a higher limit can be supported.
