### ISSUE TITLE
Support multiple versions of Hadoop in examples/tests

### ISSUE THREAD

**Issue by jeremyp-bq** [vertica/spark-connector#305]
## Is your feature request related to a problem? Please describe.

Right now our default Docker environment uses Hadoop 3.0.0, but our Kerberos environment uses Hadoop 3.1.1.  Because of this some of our scripts, such as `examples/run-example.sh`, only work for one environment or another.

We need the ability to run all examples and tests on a Kerberos or non-Kerberos environment.  And, since we can test multiple versions of Spark, we should also support multiple versions of Hadoop.

## Describe the solution you'd like

Make the Hadoop version configurable when building and running examples/tests in the same way the Spark version is configurable.  There may be additional work needed, such as having multiple versions of Hadoop available in the Docker containers.

The outcome should be that a user can run any of the examples or tests against a Kerberos or non-Kerberos environment without having to modify the scripts themselves.

## Describe alternatives you've considered

An alternative to to ensure our Kerberos and non-Kerberos environments both use the same Hadoop version, that we we can just update the scripts to reference that version.  This would be a quicker solution, but does not give us the ability to test against different versions of Hadoop.

## Additional context

To see where we use different versions, search in the repo as follows:
```sh
$ grep -r --exclude-dir=target "hadoop-3.3.0"
$ grep -r --exclude-dir=target "hadoop-3.3.1"
```

**Comment by alexey-temnikov** [comment]
Closing for now. Reopen if there is a need to automate testing with multiple Hadoop versions.
