### ISSUE TITLE
[BUG] Temporary files are not deleted after show() or cache() operation.

### ISSUE THREAD

**Issue by yunchano** [vertica/spark-connector#313]
scala> val dfRead: DataFrame = spark.read.format("com.vertica.spark.datasource.VerticaSource").options(opts).load()  
dfRead: org.apache.spark.sql.DataFrame = [sale_date_key: bigint, ship_date_key: bigint ... 16 more fields]

**# Temp files were deleted successfuly after job**
scala> dfRead.select("sale_date_key").filter("sale_date_key <=1000").count
res0: Long = 2749225  

[hadoop@hadoop001 hadoop]$ hadoop fs -find  /user -name "*parquet" -print
/user/tmp/ffed32fe_fe7a_41c7_b270_e8f7ee6075f2/online_sales_fact/7b8cd12f-v_vdb_node0001-139681734743808-0.parquet
/user/tmp/ffed32fe_fe7a_41c7_b270_e8f7ee6075f2/online_sales_fact/bb8e4195-v_vdb_node0001-139681844881152-0.parquet
/user/tmp/ffed32fe_fe7a_41c7_b270_e8f7ee6075f2/online_sales_fact/bce4fbfa-v_vdb_node0002-139668563572480-0.parquet
/user/tmp/ffed32fe_fe7a_41c7_b270_e8f7ee6075f2/online_sales_fact/c8f23cfc-v_vdb_node0003-140519791310592-0.parquet
/user/tmp/ffed32fe_fe7a_41c7_b270_e8f7ee6075f2/online_sales_fact/de47aa0d-v_vdb_node0002-139668500715264-0.parquet
/user/tmp/ffed32fe_fe7a_41c7_b270_e8f7ee6075f2/online_sales_fact/de6c9d28-v_vdb_node0003-140520321918720-0.parquet
[hadoop@hadoop001 hadoop]$ hadoop fs -find  /user -name "*parquet" -print
[hadoop@hadoop001 hadoop]$ 
[hadoop@hadoop001 hadoop]$ 

**# but after cache, temp files were not deleted**
dfRead.cache()

[hadoop@hadoop001 hadoop]$ hadoop fs -find  /user -name "*parquet" -print
/user/tmp/2c9b1051_0573_45f5_8b4b_05ec4d5ce002/online_sales_fact/251945e6-v_vdb_node0001-139681794516736-0.parquet
/user/tmp/2c9b1051_0573_45f5_8b4b_05ec4d5ce002/online_sales_fact/2a8ae318-v_vdb_node0001-139682528585472-0.parquet
/user/tmp/2c9b1051_0573_45f5_8b4b_05ec4d5ce002/online_sales_fact/cbb98415-v_vdb_node0003-140520510711552-0.parquet
/user/tmp/2c9b1051_0573_45f5_8b4b_05ec4d5ce002/online_sales_fact/d44adf57-v_vdb_node0002-139668756563712-0.parquet
/user/tmp/2c9b1051_0573_45f5_8b4b_05ec4d5ce002/online_sales_fact/e0e28781-v_vdb_node0003-140519917090560-0.parquet
/user/tmp/2c9b1051_0573_45f5_8b4b_05ec4d5ce002/online_sales_fact/fdbc0a71-v_vdb_node0002-139669182347008-0.parquet

**Comment by alexr-bq** [comment]
Thanks for the report, this is likely due to how the spark datasource API is called for cache() in a way we didn't anticipate. Will require some further investigation.
