### ISSUE TITLE
[Investigation] Read performance compared to JDBC 

### ISSUE THREAD

**Issue by alexr-bq** [vertica/spark-connector#315]
With some reports of a large difference between the connector and default spark JDBC method, investigate this. 
- In what scenarios is this true?
- Scaling bad performance vs fixed overhead
- Where in the code is responsible for this overhead/scaling?

Reason: Improves user experience if we can fix any perf issues and can improve adoption if we can show why migration to our connector improves perf

**Comment by alexey-temnikov** [comment]
A set of optimizations was implemented since that issue was raised, and it is currently missing context. In case of any future performance concerns, please reopen with more details.
