### ISSUE TITLE
[FEATURE] Prior to vertica 11 doesn't have session level parameter for AWSEnableHttps. 

### ISSUE THREAD

**Issue by yunchano** [vertica/spark-connector#321]
Spark connector V2 try to alter session for AWSEnableHttps but prior to vertica 11 doesn't support session level parameter for AWSEnableHttps.
So this connector doesn't work for prior to vertica 11 and object storage that is not configured ssl mode.

vertica=> select version(), parameter_name, allowed_levels from configuration_parameters where parameter_name = 'AWSEnableHttps';
               version               | parameter_name | allowed_levels 
-------------------------------------+----------------+----------------
 Vertica Analytic Database v10.1.1-6 | AWSEnableHttps | DATABASE

**Comment by alexr-bq** [comment]
Thanks for the report. Likely for support of this in earlier Vertica versions, we'll have to rely on the user setting this globally and skipping this step.
