### ISSUE TITLE
Support for Google GCS as temporary location fs

### ISSUE THREAD

**Issue by richiesgr** [vertica/spark-connector#376]
## Is your feature request related to a problem? Please describe.

Actually we're using databricks on GCP and we try to access our vertica DB.
The current connector seems to support hdfs and AWS S3. We would like to use GCS as you do for S3 

## Describe the solution you'd like

Add a GCS specific credential support at this moment the main problem is that the connector doesn't use the databricks global google service accout. However it's seems that we can bypass the credential system it should work  

## Describe alternatives you've considered

How to configure spark to use only config-site.xml to configure properly and grant access to GCS buckets

**Comment by Aryex** [comment]
Hi Richie, thanks for the ticket. We'll be looking into how we can support GCS with the connector.

**Comment by doubleverify-measurement** [comment]
Hi Aryex,
I've submitted a MR as I've add a partial support for GCS it's enough for us to work with.
However if you want I can add more 
talk to me

**Comment by Aryex** [comment]
Hello, 

The PR was reviewed. There are a few comments to be addressed before it can be merged.

Also, just want to confirm, that you guys are able to use GCS as the staging area with the changes you made in the PR? I'm assuming you are also using Google's [Hadoop connector](https://github.com/GoogleCloudDataproc/hadoop-connectors/tree/master/gcs) to do this.

**Comment by doubleverify-measurement** [comment]
Hi thanks for getting back to me
We use Databricks who includes all the components we need I'm sure it
includes the Hadoop FS to access GCS
However GCS authentication is a bit different than AWS S3
There no core-site.xml properties to put credentials.
So there is no need to handle these params in core-site.xml
For all other normal spark user (no databricks) I'm not sure what need to
be done.
Thanks

**Comment by Aryex** [comment]
Hello, 
We have just made PR #385  for supporting GCS with the connector. It includes the suggested changes in #378 as well as options for Spark clusters outside of GCP. Let me know if the changes work for you.
