### ISSUE TITLE
[BUG] Query connector parameter fails during table introspection

### ISSUE THREAD

**Issue by adelcast** [vertica/spark-connector#405]
## Environment
- Spark version: 3.2
- Hadoop version: 3.3.1
- Vertica version: 10.1
- Vertica Spark Connector version: 3.2.1
- Java version: openjdk 1.8.0_312

## Problem Description

The documentation states that is possible to load data from Vertica into Spark either by using the 'table' option or the 'query' option. However, when using the 'query' option I get an error that points to the table_name not being correctly parsed from the 'query' string:

Py4JJavaError: An error occurred while calling o194.showString.
: com.vertica.spark.util.error.ConnectorException: Query result is empty 
 QUERY:[SELECT data_type_id FROM columns WHERE table_name='' AND column_name='AREANAME'] 

(full stack on attached file)

I believe the connector is correctly getting all the columns in the table defined on the query, then it uses the v_catalog.columns system table to get the data_type_id for each column. However, on the generated query the table_name is left empty.

Setting the 'table' parameter does not solve the issue (by itself it works, with 'query' as well, it fails)

Below is a PySpark snippet that causes the problem:

connOptions = {
    "host" : ""####",,
    "user" : "dbadmin",
    "password" : ""####",",
    "db" : 'MYDB',
    "dbschema" : 'MYSCHEMA',
    'aws_enable_ssl' : False,
    "staging_fs_url" : "s3a://spark-staging/vertica",
    "aws_endpoint" : "####",
    "aws_access_key_id" : "####",
    "aws_secret_access_key" : "#####",
    "aws_region" : "us-east-1",
    "aws_enable_path_style" : True,
    "query" : "SELECT * FROM AREAS"
}

table = spark.read \
  .format("com.vertica.spark.datasource.VerticaSource") \
  .options(**connOptions) \
  .load()

table.show()

---
[callstack.txt](https://github.com/vertica/spark-connector/files/8782429/callstack.txt)

**Comment by Aryex** [comment]
Thanks for reporting the issue. We'll take a look into this.

**Comment by Aryex** [comment]
Hi @adelcast,

We have looked into the issue and it seems that the connector cannot support queries that produce complex types. This is because we are using the system tables in Vertica to infer complex type structures of tables and we cannot do this for queries. 

That said, this was definitely an oversight on our part to not handle this case. We have made PR #410 to address the issue.

Let me know if you have any further questions.

**Comment by adelcast** [comment]
@Aryex 

Thanks for the quick response!

I haven't tried the fix, but I was a bit thrown off since the query I am running is not returning complex types. The query is "SELECT * FROM AREAS", with the AREAS table DDL:

CREATE TABLE LAB.AREAS
(
    AREAID int NOT NULL,
    AREANAME varchar(30) NOT NULL,
    CreateTime timestamp NOT NULL,
    SchemaTypeID int,
    CONSTRAINT PK_AREAID PRIMARY KEY (AREAID) DISABLED
)
PARTITION BY (date_trunc('month', AREAS.CreateTime));

should this be expected to work?

**Comment by Aryex** [comment]
Yup, this should be addressed in the PR as well. It was a bug introduced when we added support for complex types in Vertica 10.

**Comment by adelcast** [comment]
got it, thanks again!
