### ISSUE TITLE
Create a process for Spark cluster testing

### ISSUE THREAD

**Issue by Aryex** [vertica/spark-connector#413]
## Description

We should have a process on how to create a multi-node Spark cluster and test against it. This will be useful to simulate a real-world use case where Spark applications are submitted to a remote cluster. 

Note that we should take into consideration pyspark environment, in particular Jupyter Notebook since it is a popular use case. 

Reason: Improves developer debugging by aligning dev test environment with typical user environment

**Comment by jeremyp-bq** [comment]
See also #178.
