### ISSUE TITLE
Cleanup/organization of GitHub actions and tests.

### ISSUE THREAD

**Issue by Aryex** [vertica/spark-connector#421]
## Description 
Review Github actions and see which one is needed and not.

**Comment by jeremyp-bq** [comment]
See also #402.

**Comment by Aryex** [comment]
Some notes on this issue:

For each PR, we would want some functional testing done:
- Currently, we are testing all Spark minor versions against the latest Vertica
- We could instead test all relevant Vertica versions (10, 11, latest) against the latest Spark?
- We could also just run one latest Spark against the latest Vertica. 
- We can't do much to improve the speed as runners are from Github, at high traffic times they will be slower.
- Or we don't run any functional tests? not ideal.

We can also do functional tests after each merge. This would be ideal to do more comprehensive regression testing:
- Currently testing GCS, S3, and testing against a cluster. Could be moved to weekly?
- Cluster tests could be improved. Currently has one worker but we would want at least 2 to try and mimic parallel behaviours. Potentially can be part of #303.
- We could also run the functional tests that weren't run during a PR

We also currently running a weekly test:
- Currently only testing against Vertica 10.
- We could move "low frequency" testing here. These would be tests that we believe have a low chance to fail.
- Weekly tests = 2 per iteration. Probably want them on a Monday morning.

**Comment by Aryex** [comment]
The proposal is to:

1. Keep PR testing to latest Vertica vs latest Spark
2. Provide github workflow for manual regression testing
3. Run nightly tests for:
GCS, S3, Remote, as well as regression tests.

**Comment by jeremyp-bq** [comment]
I think we should split up tests into 2 actions:
1. High priority tests run on each PR/push
2. All other tests run on a daily basis

High priority tests are against the latest or most used version of Vertica and Spark, as well as the basic test suite and any other critical features.  The daily tests would include things like older versions of Vertica and Spark, plus lesser used features like GCS and EMR.  The daily tests can also be triggered manually on a PR if a dev thinks those features may be affected or if they have made substantial changes.

I don't think we need daily and weekly, just daily should be sufficient.  Looking at the GitHub actions [limits](https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration) we should be fine to run daily, although it may be a problem when testing against third-party services (S3, GCS, and EMR).  If that is the case we could move those tests to a weekly action.
