### ISSUE TITLE
Add Jupyter notebook examples

### ISSUE THREAD

**Issue by Aryex** [vertica/spark-connector#436]
## Description

Jupyter with Spark ML or PySpark is a common use case for our users. We should look into best practices on sharing Jupyter notebook as part of the examples on the repo. This should include instruction on how to connect a Jupyter environment to a Spark-Vertica environment.

Should try to pull in connector dependencies from maven 

Reason: Helps with adoption and reduces time to get started with Spark connector.

**Comment by jeremyp-bq** [comment]
Also looking at existing Vertica examples to keep the demo experience consistent across offerings.  For example, see the Vertica Linear Regression example [here](https://www.vertica.com/docs/12.0.x/HTML/Content/Authoring/AnalyzingData/MachineLearning/LinearRegression/ProgrammingExampleLinearReg.htm).
