### ISSUE TITLE
[BUG] Loading data from vertical using the 'query' option always uses the default schema

### ISSUE THREAD

**Issue by adelcast** [vertica/spark-connector#437]
## Environment
- Spark version: 3.2
- Hadoop version: 3.3.1
- Vertica version: 10.1
- Vertica Spark Connector version: 3.2.1
- Java version:
- Additional Environment Information:

---

## Problem Description
When loading vertica data into a dataframe using the 'query' option, the 'dbschema' seems to be ignored. Prefixing the SQL tables with the schema works as expected, but this is not always convenient. In my case, I am getting the SQL from a semantic layer, which doesn't add the scheme to the table names and expects the correct schema to be configured as default.

1. Steps to reproduce:

Use spark.read.format, and define the 'query' and 'dbschema' options. Set 'dbschema' to a schema other than the default. Use a SQL query that doesn't prepend schema to the tablenames and that targets a table that only exists on dbschema. The call incorrectly fails.

2. Expected behaviour:

The 'dbschema' option should be honored when 'query' is used

3. Actual behaviour:

'dbschema' is not honored

5. Error message/stack trace:
6. Code sample or example on how to reproduce the issue:

---

## Spark Connector Logs
- Add related logs entries here.

**Comment by Aryex** [comment]
Thanks for the ticket @adelcast. We'll be taking a look at this.

**Comment by Aryex** [comment]
@adelcast We just recently opened PR #448 that will allow `dbschema` to be added to the `query`'s FROM clause table name. Let me know if it addresses your use case.

**Comment by adelcast** [comment]
it does! thanks for taking a look at this!
