### ISSUE TITLE
Review and standardize examples

### ISSUE THREAD

**Issue by Aryex** [vertica/spark-connector#446]
### Description

Our example projects should be reviewed for consistency. For example, we create an example for each functionality, but also contain a demo folder.

We should also look into adding more examples for PySpark through Jupyter Notebook.

Reason: Helps with adoption and reduces time to get started with Spark connector

**Comment by jeremyp-bq** [comment]
A few of the things I think we should consider as part of this ticket:
* Ensure all examples are consistent in the way they are laid out and executed (all examples follow the complex type structure?) - at least for a given language
* Consolidate related examples (basic, complex types, output formats, etc)
* Make sure that the instructions are clear for how to use a locally built JAR vs the using the one in Maven (which should be the default)
* Update examples to print/log information more clearly, so it is clear what they are doing and if they succeeded (also helps readability)

**Comment by Aryex** [comment]
With the goal of the examples is to ease the adoption of the connector, here are some notes on how we should update our examples:

1. Organize our examples into multiple projects by the language used. This means example projects for Scala, Python, R, and Jupyter notebooks (technically not a language). 
2. Unsure if we should include a Java example.
3. Previous Scala examples should be consolidated into a single project. Potentially make use of SBT's sub-projects which may allow for reusing common build settings like the connector's version number.
4. Unsure if Python examples should be expanded to cover the same set of examples as Scala.
5. Examples should not define a master and should instead be compiled and submitted. The user can then choose their master URL. This should decouple the examples from requiring to be run on our sandbox. 
7. We should still keep our sandbox capable of running the examples, mainly for development and testing purposes.
8. Review that examples are clear in what they are doing and what is expected, including the console outputs.
9. Review examples code to ensure they are dry and consistent in how they are written, 
10. Examples should make use of the Maven distribution of our connector instead of building it.

**Comment by jeremyp-bq** [comment]
I think it is fine for the bulk of the examples to be Scala.  A single simple read and write for the other languages is sufficient.  Preferably all languages would share this common example, although right now they all use a different dataset.

I think Java is close enough to Scala that we don't need an example for it right now.

I hope we can have an easy way to switch between using the connector from Maven (default) and the one built locally (e.g. by providing a build option).  I find it quite useful to run an example, whether as-is or slightly modified, against my locally built connector when testing.
