### ISSUE TITLE
Submit functional test to user's cluster

### ISSUE THREAD

**Issue by Aryex** [vertica/spark-connector#473]
## Is your feature request related to a problem? Please describe.

Currently, in order to submit our functional test to a cluster outside of our docker environment may not be possible as it is reading data files from hardcoded local file paths. This is an issue as:
- We would need to make the hardcoded file path be available for all nodes.
- File paths are local file system paths, thus we cannot put those on distributed file systems like hdfs or s3.
- While the fat jar contains the data files, Spark cannot read into jars. (If it can, we would also need to make the jar available for all nodes)

## Suggestions for changes.

1. Unhardcode the file paths containing the data files used by the tests.
2. Move data files out of the `resources` folder to a `data` folder.
3. Allow user to provide a custom file path to the data. Most likely through an env vars specifying the base path to the data. This would allow us to specify a path to hdfs, gcs, s3, or other file systems.
4. We should either mount the data folder in our docker containers or copy it onto our hdfs. (Note that the startup scripts is doing some data copying to hdfs)

**Comment by alexey-temnikov** [comment]
To be implemented if there is a need in the future.
