### ISSUE TITLE
Flakey CI Tests

### ISSUE THREAD

**Issue by Aryex** [vertica/spark-connector#484]
# Descriptions
Our nightly tests and weekly tests would randomly fails when trying to do a docker-compose up. This seems to always happen to our jobs using a matrix, and we have only observed one run failing, but no more. The failure seems to always happen with hdfs container, and the error is from "a port is not available". 

Re-running the failed tests and it would pass. We are unsure if this has something to do with running too many parallel jobs using matrices.

**Comment by jeremyp-bq** [comment]
Last failure was under the Weekly Tests was on September 2.  The failing test was the second in the matrix (`Vertica ([3.0.0, 3.1.0), 2.7.4, 12.0.0-0)`), once again complaining about the HDFS port 50020 not being available.

Will continue to monitor this issue to see if the additional `docker compose down` helps.
