### ISSUE TITLE
[BUG] Scrutinize doesn't track which connections are spark connections

### ISSUE THREAD

**Issue by NerdLogic** [vertica/spark-connector#494]
## Problem Description
- Issue #115 didn't set the label early enough, so dc_sessioin_starts doesn't contain the correct client label.  I believe that if we set it in the connection properties that are passed into getConnection(), then dc_session_starts will show vspark-* in the client label and scrutinize will contain that data.

1. Steps to reproduce:
  run scrutinize report.
3. Expected behaviour:
  vspark in client label of dc_session_starts 
4. Actual behaviour:
  jdbc in client label

**Comment by jeremyp-bq** [comment]
Should be able to add the following to VerticaJdbcLayer.scala to ensure the connection sets the client label on connection creation:
```
prop.put("LABEL", this.createClientLabel)
```

We should also consider updating the Vertica documentation to include this information.  I only see references to APPLICATIONNAME, not LABEL (e.g. [here](http://documentation.verticacorp.com/master/HTML/Content/Authoring/ConnectingToVertica/ClientJDBC/SettingAndReturningAClientConnectionLabel.htm?Highlight=applicationname) and [here](http://documentation.verticacorp.com/master/HTML/Content/Authoring/ConnectingToVertica/ClientDriverMisc/SettingAClientConnectionLabel.htm?Highlight=applicationname)).
