### ISSUE TITLE
What's the difference between assets published in git releases and maven?

### ISSUE THREAD

**Issue by vladpy8** [vertica/spark-connector#521]
There are several ways to obtain jars required:

https://github.com/vertica/spark-connector/releases/tag/v3.3.4

https://mvnrepository.com/artifact/com.vertica.spark/vertica-spark/3.3.4

What's the difference between them?

I am working with pyspark and have to manually (at least for now) add jars to spark distribution. And I am not sure which one is better

Thanks

**Comment by jeremyp-bq** [comment]
The JARs under the GitHub release page and the JARs in Maven should be exactly the same.  So you can use whatever method works best for you.

We provide two kinds of JARs, shaded (default) and slim.  The shaded JAR is much larger and also contains all of the dependencies (Spark, Hadoop, etc), as long as those dependencies don't clash with other versions you are already using.  The slim JAR contains just the Spark Connector code, so you'll also have to download all of the dependency JARs separately.

For example, for version 3.3.4:
* Shaded
    * https://mvnrepository.com/artifact/com.vertica.spark/vertica-spark/3.3.4
    * https://github.com/vertica/spark-connector/releases/download/v3.3.4/spark-vertica-connector-all-3.3.4.jar
* Slim
    * https://mvnrepository.com/artifact/com.vertica.spark/vertica-spark/3.3.4-slim
    * https://github.com/vertica/spark-connector/releases/download/v3.3.4/spark-vertica-connector-slim-3.3.4.jar
